# Generated by Django 5.0.2 on 2024-06-25 22:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="card",
            name="chinese",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="card",
            name="pinyin",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="card",
            name="translation",
            field=models.CharField(default="", max_length=255),
        ),
    ]
