# Generated by Django 5.0.2 on 2024-07-13 15:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_card_chinese_card_pinyin_card_translation"),
    ]

    operations = [
        migrations.AddField(
            model_name="card",
            name="ease",
            field=models.FloatField(default=2.5),
        ),
        migrations.AddField(
            model_name="card",
            name="interval",
            field=models.PositiveBigIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="card",
            name="repetition",
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="card",
            name="chinese",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="card",
            name="pinyin",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="card",
            name="translation",
            field=models.CharField(max_length=255),
        ),
    ]
