# Generated by Django 5.0.2 on 2024-07-13 15:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_card_ease_card_interval_card_repetition_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="card",
            name="chinese",
            field=models.CharField(max_length=255),
        ),
    ]
