# Generated by Django 5.0.2 on 2024-07-13 15:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_alter_card_chinese"),
    ]

    operations = [
        migrations.AlterField(
            model_name="card",
            name="chinese",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
